apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service.calc }}
spec:
  selector:
    app: {{ .Values.names.app.calc }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}