apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service.web }}
spec:
  selector:
    app: {{ .Values.names.app.web }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}